// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PowerFantasy.ApiService.Data;

#nullable disable

namespace PowerFantasy.ApiService.Data.Migrations
{
    [DbContext(typeof(PowerFantasyDbContext))]
    partial class PowerFantasyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PowerFantasy.ApiService.Data.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommissionerUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SleeperLeagueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PublicSlug")
                        .IsUnique();

                    b.HasIndex("SleeperLeagueId")
                        .IsUnique();

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("PowerFantasy.ApiService.Data.PollVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("RankedTeamIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VoterTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WeeklyPollId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VoterTeamId");

                    b.HasIndex("WeeklyPollId", "VoterTeamId")
                        .IsUnique();

                    b.ToTable("PollVotes");
                });

            modelBuilder.Entity("PowerFantasy.ApiService.Data.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PointsAgainst")
                        .HasColumnType("double precision");

                    b.Property<double>("PointsFor")
                        .HasColumnType("double precision");

                    b.Property<string>("SleeperOwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SleeperRosterId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ties")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "SleeperRosterId")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PowerFantasy.ApiService.Data.WeeklyPoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "Season", "Week")
                        .IsUnique();

                    b.ToTable("WeeklyPolls");
                });

            modelBuilder.Entity("PowerFantasy.ApiService.Data.PollVote", b =>
                {
                    b.HasOne("PowerFantasy.ApiService.Data.Team", null)
                        .WithMany()
                        .HasForeignKey("VoterTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerFantasy.ApiService.Data.WeeklyPoll", null)
                        .WithMany()
                        .HasForeignKey("WeeklyPollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PowerFantasy.ApiService.Data.Team", b =>
                {
                    b.HasOne("PowerFantasy.ApiService.Data.League", null)
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PowerFantasy.ApiService.Data.WeeklyPoll", b =>
                {
                    b.HasOne("PowerFantasy.ApiService.Data.League", null)
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
