@ApiService_HostAddress = http://localhost:5312

GET {{ApiService_HostAddress}}/api/teams
Accept: application/json

###

GET {{ApiService_HostAddress}}/api/polls/current
Accept: application/json

###

GET {{ApiService_HostAddress}}/api/polls/history
Accept: application/json

###
